name: Release Build

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone PKHeX.Core only (shallow)
        run: |
          git clone --depth 1 https://github.com/kwsch/PKHeX.git PKHeX

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Read version from Directory.Build.props
        id: version
        shell: pwsh
        run: |
          $xml = [xml](Get-Content Directory.Build.props)
          $v = $xml.Project.PropertyGroup.Version
          echo "version=$v" >> $env:GITHUB_OUTPUT

      - name: Fail if version not found
        if: steps.version.outputs.version == ''
        run: exit 1

      - name: Build PKHeX.Core
        run: dotnet build PKHeX/PKHeX.Core/PKHeX.Core.csproj -c Release

      - name: Run tests
        run: dotnet test Generator.Tests/Generator.Tests.csproj

      - name: Publish self-contained EXE
        run: |
          dotnet publish Generator/Generator.csproj -c Release -r win-x64 --self-contained true `
            -p:PublishSingleFile=true `
            -p:UseAppHost=true `
            -p:IncludeNativeLibrariesForSelfExtract=true

      - name: Zip executable
        run: Compress-Archive -Path Generator/bin/Release/net9.0/win-x64/publish/generator.exe -DestinationPath generator.zip

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          generate_release_notes: true
          files: generator.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
